environment:  

  matrix:  

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      generator: "Visual Studio 17 2022"
      arch: x64
      configuration: Debug
      output_name_postfix: _d

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      generator: "Visual Studio 17 2022"
      arch: x64
      configuration: Release 
  
install:
  - cmake --version
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan profile detect --force
  - conan --version
  
build_script:
  - cd tests
  - conan install . --output-folder=build --build=missing --settings=build_type=%configuration%
  - cd build
  - cmake -G "%generator%" -A "%arch%" .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake"
  - cmake --build . --config %configuration%
   
after_build:
   - cd bin
   - blopp_tests%output_name_postfix%.exe