name: Fuzz
on: push

jobs:

  linux:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          compiler:
            - cc: clang-16
              cxx: clang++-16
          build_type: [Debug, Release]
          include:
            - build_type: Debug
              output_name_postfix: _d

    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM and Clang
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/focal llvm-toolchain-focal-16 main' -y
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install build-essential clang-16
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-16 90
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-16 90

      - name: Build
        run: |
          cd fuzz
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
          cmake --build . --config ${{matrix.build_type}}
        env:
          CC: ${{matrix.compiler.cc}}
          CXX: ${{matrix.compiler.cxx}}

      - name: Fuzz
        run: |
          cd fuzz/bin
          mkdir corpus
          ./blopp_fuzz${{matrix.output_name_postfix}} corpus -max_total_time=100 -timeout=60

 